services:

  admin_panel:
    restart: always
    build: ../admin-panel/
    command: >
      sh -c "cd /app/src/
      && mkdir -p media
      && uv run manage.py collectstatic --noinput
      && uv run manage.py migrate --noinput
      && uv run manage.py createsuperuser --noinput || true
      && uv run gunicorn --reload -c gunicorn.py config.wsgi:application"
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/src/static/
      - media_volume:/app/src/media/
    environment:
      - "DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}"
      - "DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}"
      - "DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}"
      - "SECRET_KEY=${SECRET_KEY}"
      - "DEBUG=False"
      - "DB_NAME=${NOTIFICATIONS_DB_NAME}"
      - "DB_USER=${NOTIFICATIONS_DB_USER}"
      - "DB_PASSWORD=${NOTIFICATIONS_DB_PASSWORD}"
      - "DB_HOST=notifications_db"
      - "DB_PORT=5432"
    depends_on:
      - notifications_db

  receiver:
    restart: always
    build: ../receiver/
    command: >
      sh -c "cd /app/src/
      && poetry run python main.py"
    expose:
      - "5000"
    ports:
      - "5000:5000"
    environment:
      - "FASTAPI_PORT=5000"
      - "DEBUG=False"
      - "RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}"
      - "RABBITMQ_PASS=${RABBITMQ_DEFAULT_PASS}"
      - "RABBITMQ_HOST=rabbit"
      - "RABBITMQ_SERVER_PORT=15672"
      - "RABBITMQ_CLIENT_PORT=5672"
      - "POSTGRES_HOST=notifications_db"
      - "POSTGRES_PORT=5432"
      - "POSTGRES_NAME=${NOTIFICATIONS_DB_NAME}"
      - "POSTGRES_USER=${NOTIFICATIONS_DB_USER}"
      - "POSTGRES_PASSWORD=${NOTIFICATIONS_DB_PASSWORD}"
    depends_on:
      - rabbit
      - notifications_db

  worker:
    restart: always
    build: ../worker/
    command: >
      sh -c "cd /app/src/
      && poetry run python main.py"
    environment:
      - "RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}"
      - "RABBITMQ_PASS=${RABBITMQ_DEFAULT_PASS}"
      - "RABBITMQ_HOST=rabbit"
      - "RABBITMQ_SERVER_PORT=15672"
      - "RABBITMQ_CLIENT_PORT=5672"
      - "POSTGRES_HOST=notifications_db"
      - "POSTGRES_PORT=5432"
      - "POSTGRES_NAME=${NOTIFICATIONS_DB_NAME}"
      - "POSTGRES_USER=${NOTIFICATIONS_DB_USER}"
      - "POSTGRES_PASSWORD=${NOTIFICATIONS_DB_PASSWORD}"
      - "SMTP_SERVER=${SMTP_SERVER}"
      - "SMTP_PORT=${SMTP_PORT}"
      - "SMTP_USER=${SMTP_USER}"
      - "SMTP_PASSWORD=${SMTP_PASSWORD}"
    depends_on:
      - rabbit
      - notifications_db

  notifications_db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=${NOTIFICATIONS_DB_USER}"
      - "POSTGRES_PASSWORD=${NOTIFICATIONS_DB_PASSWORD}"
      - "POSTGRES_DB=${NOTIFICATIONS_DB_NAME}"

  rabbit:
    image: rabbitmq:4-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    environment:
      - "RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}"
      - "RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}"

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/src/static
      - media_volume:/app/src/media
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - admin_panel

volumes:
  static_volume:
  media_volume:
