[project]
name = "postgres-to-mongo"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "psycopg2-binary==2.9.10",
    "pymongo==4.11.3",
    "redis==5.2.1",
]
