services:

  admin_panel:
    restart: always
    build: ../.
    command: >
      sh -c "cd /app/src/
      && mkdir -p media
      && python manage.py collectstatic --noinput
      && python manage.py migrate --noinput
      && python manage.py createsuperuser --noinput || true
      && gunicorn --reload -c ../infra/gunicorn/gunicorn_config.py config.wsgi:application"
    expose:
      - "8000"
    volumes:
      - static_volume:/app/src/static/
      - media_volume:/app/src/media/
    environment:
      - "DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}"
      - "DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}"
      - "DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}"
      - "SECRET_KEY=${SECRET_KEY}"
      - "DEBUG=False"
      - "DB_NAME=${DB_NAME}"
      - "DB_USER=${DB_USER}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "DB_HOST=${DB_HOST}"
      - "DB_PORT=${DB_PORT}"
    depends_on:
      - movies_db

  movies_db:
    build: ../infra/postgres/
    restart: always
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=${DB_NAME}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    volumes:
        - movies_db_volume:/var/lib/postgresql/data/

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/src/static
      - media_volume:/app/src/media
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - admin_panel

volumes:
  movies_db_volume:
  static_volume:
  media_volume:
