[project]
name = "postgres-to-elastic"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "elasticsearch==8.17.2",
    "psycopg2-binary==2.9.10",
    "pydantic==2.11.1",
    "redis==5.2.1",
]
