services:

  movies_ugc:
    restart: always
    build: ../..
    command: >
      sh -c "cd /app/src/
      && python main.py"
    volumes:
      - ../..:/app
    environment:
      - "FASTAPI_PORT=8080"
      - "MONGO_PORT=27017"
      - "DEBUG=True"
      - "JWT_SECRET_KEY=secretkey"
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:8.0.1
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 5s
      timeout: 5s
      retries: 100

volumes:
  movies_db_volume:
