services:

  postgres_to_elastic:
    restart: always
    build: ../postgres-to-elastic/
    command: >
      sh -c "cd /app/src/
      && python main.py"
    environment:
      - "DB_NAME=${MOVIES_DB_NAME}"
      - "DB_USER=${MOVIES_DB_USER}"
      - "DB_PASSWORD=${MOVIES_DB_PASSWORD}"
      - "DB_HOST=movies_db"
      - "DB_PORT=5432"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "REDIS_DB=0"
    depends_on:
      movies_db:
        condition: service_healthy
      redis:
        condition: service_healthy
      elastic:
        condition: service_healthy

  postgres_to_mongo:
    restart: always
    build: ../postgres-to-mongo/
    command: >
      sh -c "cd /app/src/
      && python main.py"
    environment:
      - "MOVIES_DB_NAME=${MOVIES_DB_NAME}"
      - "MOVIES_DB_USER=${MOVIES_DB_USER}"
      - "MOVIES_DB_PASSWORD=${MOVIES_DB_PASSWORD}"
      - "MOVIES_DB_HOST=movies_db"
      - "MOVIES_DB_PORT=5432"
      - "AUTH_DB_NAME=${AUTH_DB_NAME}"
      - "AUTH_DB_USER=${AUTH_DB_USER}"
      - "AUTH_DB_PASSWORD=${AUTH_DB_PASSWORD}"
      - "AUTH_DB_HOST=auth_db"
      - "AUTH_DB_PORT=5432"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "REDIS_DB=0"
    depends_on:
      mongo:
        condition: service_healthy
      movies_db:
        condition: service_healthy
      auth_db:
        condition: service_healthy
      redis:
        condition: service_healthy

  movies_db:
    build: ../../admin-panel/infra/postgres/
    restart: always
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=${MOVIES_DB_USER}"
      - "POSTGRES_PASSWORD=${MOVIES_DB_PASSWORD}"
      - "POSTGRES_DB=${MOVIES_DB_NAME}"
    volumes:
      - movies_db_volume:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready --dbname=${MOVIES_DB_NAME} --username=${MOVIES_DB_USER}
      interval: 5s
      timeout: 5s
      retries: 100

  auth_db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_USER=${AUTH_DB_USER}"
      - "POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}"
      - "POSTGRES_DB=${AUTH_DB_NAME}"
    volumes:
      - auth_db_volume:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready --dbname=${AUTH_DB_NAME} --username=${AUTH_DB_USER}
      interval: 5s
      timeout: 5s
      retries: 100

  elastic:
    image: elasticsearch:8.13.0
    expose:
      - "9200"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ports:
      - "9200:9200"
    healthcheck:
      test: curl -s http://elastic:9200 >/dev/null || exit 1
      interval: 5s
      timeout: 5s
      retries: 100

  mongo:
    image: mongo:8.0.1
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 5s
      timeout: 5s
      retries: 100

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 5s
      retries: 100

  kibana:
    image: kibana:8.13.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200
    depends_on:
      elastic:
        condition: service_healthy

volumes:
  movies_db_volume:
  auth_db_volume:
