services:

  movies_api:
    restart: always
    build: ../.
    command: >
      sh -c "cd /app/src/
      && python main.py"
    environment:
      - "FASTAPI_PORT=8000"
      - "ELASTIC_HOST=elastic"
      - "ELASTIC_PORT=9200"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "REDIS_DB=1"
    expose:
      - "8000"
    depends_on:
      elastic:
        condition: service_healthy
      redis:
        condition: service_healthy

  elastic:
    image: elasticsearch:8.13.0
    expose:
      - "9200"
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    healthcheck:
      test: curl -s http://elastic:9200 >/dev/null || exit 1
      interval: 5s
      timeout: 5s
      retries: 100

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 5s
      retries: 100

  elasticdump:
    image: elasticdump/elasticsearch-dump
    depends_on:
      elastic:
        condition: service_healthy
    volumes:
      - /data:/tmp
    entrypoint: >
      sh -c "sleep 10 && elasticdump \
      --input=/tmp/dump.json \
      --output=http://elastic:9200 \
      --type=data"

  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - movies_api
