version: '3.8'

services:

  auth:
    restart: always
    build: ../..
    command: >
      sh -c "cd /app/src/
      && python manage.py"
    volumes:
      - ../..:/app
    expose:
      - "5000"
    ports:
      - "5000:5000"

