services:

  auth:
    restart: always
    build: ../..
    command: >
      sh -c "cd /app/src/
      && uv run flask --app manage:create_app migrate
      && uv run manage.py"
    volumes:
      - ../..:/app
    expose:
      - "5000"
    ports:
      - "5000:5000"
    environment:
      - "JWT_SECRET_KEY=jwtsecretkey"
      - "SECRET_KEY=secretkey"
      - "FLASK_PORT=5000"
      - "DEBUG=True"
      - "DB_NAME=postgres"
      - "DB_USER=postgres"
      - "DB_PASSWORD=postgres"
      - "DB_HOST=auth_db"
      - "DB_PORT=5432"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "REDIS_DB=1"
      - "NOTIFICATIONS_RECEIVER_HOST=${NOTIFICATIONS_RECEIVER_HOST}"
      - "NOTIFICATIONS_RECEIVER_PORT=${NOTIFICATIONS_RECEIVER_PORT}"

  auth_db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=auth"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=postgres"
    volumes:
        - auth_db_volume:/var/lib/postgresql/data/

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

volumes:
  auth_db_volume:
